#' MERCI DNA rank (Neff counts) calculation
#'
#' This function calculated the MERCI DNA rank based on the counts of identified donor cell enriched mtSNVs in each input cell.
#' @param varMatrix the processed vaf matrix of mtSNV generated by MTmutMatrix_transform function.
#' @param MT_variants the original mtSNV table as the output file generated by readMTvar_10x or readMTvar function.
#' @param MT_coverage matrix of Mitochondrial coverage inforamtion (row indicates MT genome locus and column indicates cell), such as the variables generated by readCoverage_10x or readCoverage function.
#' @param donor_cells the list of cell names for mitochondrial donor cells.
#' @param mixed_cells the list of cell names for candidate receiver cells, they should be mixed cells with unknown ratio of receirves vs non-receivers.
#' @param Ref_nonReceivers Only for regular MERCI pipeline, the list of cell names for reference non-receivers. IF not provied, the default is NULL, which means MERCI LOO pipeline will be used.
#' @param mutFeatures the list of mutation id for donor cell enriched mtSNVs, which can be obtained from Denrich_mtMut_extr function.
#' @param adjust whether adjusting the count statistics into Neff (No.effective count) statistics. when adjust=FALSE, then the original count of observed donor-enriched mtSNV in each candidate receiver cell will be used to calculate the DNA rank. Default=FALSE.
#' @param adjust.method Denotes which method to use when adjust=TRUE, Available options are: 'Roe' weight will be calculated as observed(mi)/expected(mi); 'LR' weight will be calculated as the ratio of marinal likelihoods Pi/Qi. When adjust=FALSE, this parameter will be ignored. Default='Roe'.
#' @param frac_tran whether using the fraction rather than count/Neff to calculate the DNA rank. Default=FALSE
#' @param e sequencing error, default=0.001.
#' @return a data.frame with count/Neff statistics for all mixed_cells and the transformed DNA ranks.
#' @export
#' @examples Cell_Neff_cal(varMatrix, MT_variants, MT_coverage, donor_cells, mixed_cells, mutFeatures)

Cell_Neff_cal <- function(varMatrix, MT_variants, MT_coverage, donor_cells, mixed_cells, Ref_nonReceivers=NULL, mutFeatures, adjust=TRUE, adjust.method='Roe', frac_tran=FALSE, e=0.001)
{	
	if(!all(mixed_cells%in%colnames(varMatrix)))
	{
		print('Error: some input cell are not included in the varMatrix!')
		return()
	}
	
	t_varMatrix2 <- varMatrix[mutFeatures, mixed_cells] ;
	
	if(!adjust)
	{
		mut_numbers <- apply(t_varMatrix2, 2, function(x) {
			sum(x > 0, na.rm=TRUE) ;
		})
		boxplot(mut_numbers, main='Counts of Donor enriched mtSNVs in input mixed cells!') ;
		
		mut_number_frac <- apply(t_varMatrix2, 2, function(x) {
			sum(x > 0, na.rm=TRUE)/sum(x >= 0, na.rm=TRUE) ;
		})
		
		MTvar_rank <- mut_numbers ;
		MTvar_rank[order(mut_numbers)] <- 1:length(MTvar_rank) ;
		
		MTvar_frac_rank <- mut_number_frac ;
		MTvar_frac_rank[order(MTvar_frac_rank)] <- 1:length(MTvar_frac_rank) ;
		
		if(frac_tran==TRUE)
		{	t.results <- cbind.data.frame(DMTvar_count=mut_number_frac, MTvar_rank=MTvar_frac_rank) ; } else {
			t.results <- cbind.data.frame(DMTvar_count=mut_numbers, MTvar_rank=MTvar_rank) ; 
		}
		return(t.results)
	}
	
	if(is.null(Ref_nonReceivers))
	{
		muts_inf <- mut_inf_extr(muts=mutFeatures, donor_cell_ref=donor_cells, receiver_cell_ref=mixed_cells, mutMatrix_processed=varMatrix, MT_variants=MT_variants, MT_coverage=MT_coverage) ;
	} else {
		muts_inf <- mut_inf_extr(muts=mutFeatures, donor_cell_ref=donor_cells, receiver_cell_ref=Ref_nonReceivers, mutMatrix_processed=varMatrix, MT_variants=MT_variants, MT_coverage=MT_coverage) ;
	}
	
	if(adjust & adjust.method=='Roe')
	{
		DepthNorm_counts <- sapply(mixed_cells, function(t_cell) {
			W <-  w_cal(mutFeatures, t_cell, muts_inf, varMatrix, MT_coverage, e=e) ;
			N <- sum(W>1, na.rm=TRUE) ;
			F <- sum(W>1, na.rm=TRUE)/sum(!is.na(W)) ;
			return(c(N, F)) ;
		})
		DepthNorm_counts <- t(DepthNorm_counts) ;
	}
	
	if(adjust & adjust.method=='LR')
	{
		DepthNorm_counts <- sapply(mixed_cells, function(t_cell) {
			W <-  w_cal2(mutFeatures, t_cell, muts_inf, varMatrix, MT_coverage, e=e) ;
			N <- sum(W>1, na.rm=TRUE) ;
			F <- sum(W>1, na.rm=TRUE)/sum(!is.na(W)) ;
			return(c(N, F)) ;
		})
		DepthNorm_counts <- t(DepthNorm_counts) ;
	}
	boxplot(DepthNorm_counts[,1], main='Neff statistics of Donor enriched mtSNV in input mixed cells!') ;

	
	MTvar_rank <- DepthNorm_counts[,1] ;
	MTvar_rank[order(DepthNorm_counts[,1])] <- 1:length(MTvar_rank) ;
	
	MTvar_frac_rank <- DepthNorm_counts[,2] ;
	MTvar_frac_rank[order(DepthNorm_counts[,2])] <- 1:length(MTvar_frac_rank) ;
	
	if(frac_tran==TRUE)
	{	t.results <- cbind.data.frame(DMTvar_count=DepthNorm_counts[,2], MTvar_rank=MTvar_frac_rank) ; } else {
		t.results <- cbind.data.frame(DMTvar_count=DepthNorm_counts[,1], MTvar_rank=MTvar_rank) ; 
	}	
	return(t.results)
}

