#' Identification of donor cell-enriched mtSNVs
#'
#' This function will identify the a list mitochondrial variants that are more frequently observed in donor cells
#' @param varMatrix the processed vaf matrix of mtSNV generated by MTmutMatrix_refined function.
#' @param donor_cells the list of cell names for mitochondrial donor cells.
#' @param mixed_cells the list of cell names for candidate receiver cells, they should be mixed cells with unknown ratio of receirves vs non-receivers.
#' @param Ref_nonReceivers Only for regular MERCI pipeline, the list of cell names for reference non-receivers. If provided, then the donor cell-enriched mtSNVs will be obtained by comparing mtSNVs in donor_cells with Ref_nonReceivers, otherwise Ref_nonReceivers will be set as NULL and all mixed_cells will be used as the reference non-recievers to get the donor cell-enriched mtSNVs.
#' @param OR Only return the mtSNVs with odds ratio (donor cells vs reference non-reciever cells) > OR, default=2.
#' @param Nmut_min the minimum requirement for mutated cell counts, only the mtSNVs with mutated cell counts > Nmut_min will be further used to test if it is a donor cell enriched mtSNV.
#' @param pvalue Only return the mtSNVs with statistical p <= pvalue (chi-squre test), defualt=1.
#' @param qvalue Only return the mtSNVs with ajusted p value from BH method <= qvalue, default=1.
#' @export
#' @examples Denrich_mtMut_extr(varMatrix, donor_cells, mixed_cells, OR=2)
Denrich_mtMut_extr <- function(varMatrix, donor_cells, mixed_cells, Ref_nonReceivers=NULL, OR=2, Nmut_min=5, pvalue=1, qvalue=1) 
{
	if(length(donor_cells)<50)
	{ print('warninging, the count of provided donor cells is not enough (n < 50), which is not sufficient for donor-enriched mtSNV identification！') }

	if(is.null(Ref_nonReceivers))
	{
		print('no Ref_nonReceivers are provided, cells in mixed_cells will be used as referece nonReceivers!')
		muts <- Donor_enriched_vars(varMatrix, donor_cells, mixed_cells, Nmut_min=Nmut_min, pvalue=pvalue, qvalue=qvalue, OR=OR) ;
	} else {
		print(paste('There are', length(Ref_nonReceivers),'cells as the reference non-receivers.' ))
		muts <- Donor_enriched_vars(varMatrix, donor_cells, Ref_nonReceivers, Nmut_min=Nmut_min, pvalue=pvalue, qvalue=qvalue, OR=OR) ;
	}
	
	print(paste(length(muts), ' donor enriched mtSNVs were identified!') ) ;
	return(muts) ;
}

