#' DNA rank calculation
#'
#' This function identifys the donor cell enriched mtSNVs and calculated the MERCI DNA rank based on the counts of identified mtSNVs in each input cell.
#' @param varMatrix the processed vaf matrix of mtSNV generated by MTmutMatrix_refined function.
#' @param MT_coverage Mitochondrial coverage inforamtion, such as the variables generated by readCoverage_10x or readCoverage function.
#' @param MT_coverage Mitochondrial coverage inforamtion, such as the variables generated by readCoverage_10x or readCoverage function.
#' @param donor_cells the list of cell names for mitochondrial donor cells.
#' @param mixed_cells the list of cell names for supposed receiver cells, they should be mixed cells with unknown ratio of receirves vs non-receivers.
#' @Ref_nonReceivers Only for regular MERCI pipeline, the list of cell names for reference non-receivers. IF not provied, the default is NULL, which means MERCI LOO pipeline will be used.
#' @param min_d the minimum read coverage required for each mtSNV in different cells, the mutation record will be considered as 'unobservable' and set as NA if the the coverage at the mutation locus < min_d, default=5.
#' @param min_observeRate the minimum requirement for observatiion Rate (see parameter min_d), eahc mtSNV will be removed if its observeRate < min_observeRate, default=10%.
#' @param Nmut_min the minimum requirement for mutated cell counts, only the mtSNVs with mutated cell counts > Nmut_min will be further used to test if it is a donor cell enriched mtSNV.
#' @param pvalue Only return the mtSNVs with statistical p <= pvalue (chi-squre test), defualt=0.05.
#' @param qvalue Only return the mtSNVs with ajusted p value from BH method <= qvalue, default=0.1.
#' @param OR Only return the mtSNVs with odds ratio (T cells vs reciever_cells) > OR, default=1.
#' @return a data.frame with counts of donor cell enriched mtSNVs for all mixed_cells and the DNA ranks.
#' @export
#' @examples MERCI_MTvar_cal(varMatrix, MT_coverage, donor_cells, mixed_cells)

MERCI_MTvar_cal <- function(varMatrix=mutMatrix_Hcover, MT_coverage, donor_cells, mixed_cells, Ref_nonReceivers=NULL, min_d=5, min_observeRate= 0.1, Nmut_min=5, pvalue=0.05, qvalue=1, OR=1)
{
	mixed_cells <- intersect(mixed_cells, colnames(varMatrix)) ;
	donor_cells <- intersect(donor_cells, colnames(varMatrix)) ;
	
	print(paste('There are', length(mixed_cells), 'supposed mixed cells with MT variants information in varMatrix!') ) ;
	print(paste('There are', length(donor_cells), 'supposed donor cells with MT variants information in varMatrix!'))
	
	if(length(donor_cells)<50)
	{ print('warninging, the available donor cells < 50!') }
	
	mutMatrix_processed <- filter_MTmuts(varMatrix, MT_coverage, donor_cells=donor_cells, reciever_cells=c(mixed_cells, Ref_nonReceivers), min_d=min_d, min_observeRate=min_observeRate) ; #31,550
	
	if(is.null(Ref_nonReceivers))
	{
		muts <- Donor_enriched_vars(mutMatrix_processed, donor_cells, mixed_cells, Nmut_min=Nmut_min, pvalue=pvalue, qvalue=qvalue, OR=OR) ;
	} else {
		print(paste('There are', length(Ref_nonReceivers),'cells as the reference non-receivers.' ))
		muts <- Donor_enriched_vars(mutMatrix_processed, donor_cells, Ref_nonReceivers, Nmut_min=Nmut_min, pvalue=pvalue, qvalue=qvalue, OR=OR) ;
	}
	
	print(paste(length(muts), ' donor enriched MTvariants were identified!') ) ;

	t_varMatrix2 <- mutMatrix_processed[muts, mixed_cells] ;
	mut_numbers <- apply(t_varMatrix2, 2, function(x) {
	sum(x > 0, na.rm=TRUE) ;
	})
	boxplot(mut_numbers, main='Donor enriched mtSNV counts in input mixed cells') ;
	
	MTvar_rank <- mut_numbers ;
	MTvar_rank[order(mut_numbers)] <- 1:length(MTvar_rank) ;
	
	t.results <- cbind.data.frame(DMTvar_count=mut_numbers, MTvar_rank=MTvar_rank) ;
	return(t.results)
}

