#' Preprocess the mtSNV table and generate the vaf matrix
#'
#' This function generates a vaf matrix with rows as mtSNV and columns as cells
#' @param MT_variants the mtSNV table with format the same as variables generated by readMTvar_10x or readMTvar function.
#' @param MT_coverage the mitochondrial coverage information with content the same as variables generated by readCoverage_10x or readCoverage function.
#' @param donor_cells the list of cell names for mitochondrial donor cells.
#' @param mixed_cells the list of cell names for candidate receiver cells, they should be mixed cells with unknown ratio of receirves vs non-receivers.
#' @param Ref_nonReceivers Only for regular MERCI pipeline, the list of cell names for reference non-receivers. IF not provied, the default is NULL, which means MERCI LOO pipeline will be used.
#' @param min_d the minimum read coverage required for each mtSNV in different cells, the mutation record will be considered as 'unobservable' and set as NA if the the coverage at the mutation locus < min_d, default=5.
#' @param min_observeRate the minimum requirement for observatiion Rate (see parameter min_d), any mtSNV with observeRate < min_observeRate will be removed, default=10%.
#' @return a processed vaf matrix, if the locus of mtSNV have no covered read or read number < min_d in one sample, the corresponding value was set as NA.
#' @export
#' @examples MTmutMatrix_transform(MT_variants, MT_coverage, donor_cells, mixed_cells)

MTmutMatrix_transform  <- function(MT_variants, MT_coverage, donor_cells, mixed_cells, Ref_nonReceivers=NULL, min_d=5, min_observeRate= 0.1) 
{
	varMatrix <- MTmutMatrix_refined(MT_variants, MT_coverage) ;
	mixed_cells <- intersect(mixed_cells, colnames(varMatrix)) ;
	donor_cells <- intersect(donor_cells, colnames(varMatrix)) ;
	
	print(paste('There are', length(mixed_cells), 'supposed mixed cells with MT variants information!')) ;
	print(paste('There are', length(donor_cells), 'supposed donor cells with MT variants information!')) ;
	
	mutMatrix_processed <- filter_MTmuts(varMatrix, MT_coverage, donor_cells=donor_cells, reciever_cells=c(mixed_cells, Ref_nonReceivers), min_d=min_d, min_observeRate=min_observeRate) ; #31,550

	return(mutMatrix_processed)
}


