#' Generate the vaf matrix
#'
#' This function generates a vaf matrix with rows as mtSNV and columns as cells
#' @param MT_variants the mtSNV table with format the same as variables generated by readMTvar_10x or readMTvar function.
#' @param coverage the mitochondrial coverage information with content the same as variables generated by readCoverage_10x or readCoverage function.
#' @return a processed vaf matrix, if the locus of mtSNV have no covered read in one sample, the corresponding value was set as NA.
#' @export
#' @examples MTmutMatrix_refined(MT_variants, coverage)

MTmutMatrix_refined <- function(MT_variants, coverage) 
{
	mut_matrix <- tapply(MT_variants$AF, list(MT_variants$ID, MT_variants$Cell), function(x) {x} ) ;
	print(paste(nrow(mut_matrix), "variants and", ncol(mut_matrix), "cells were used!") ) ;
	Var_positions <- sapply(strsplit(rownames(mut_matrix), "_" ), function(x) x[2]);
	used_cells <- colnames(mut_matrix) ;
	if( sum(!used_cells%in%colnames(coverage))>0 )
	{
		print('Error: some cells do not have coverage information!')
		return(NULL)
	}
	
	cell_coverage <- coverage[Var_positions, used_cells] ;
	t_index1 <- is.na(mut_matrix) ;
	t_index2 <- cell_coverage > 0 ;
	t_index3 <- t_index1 & t_index2 ;
	t.results <- mut_matrix ;
	t.results[t_index3] <- 0 ;
	return(t.results)
}

