#' mutation annotation for a specified mutation list
#'
#' This function extracted the detailed mutation annotation.
#' @param muts the mitochondrial mutation list.
#' @param donor_cell_ref reference donor cells.
#' @param mutMatrix_processed the processed vaf matrix of mtSNV generated by MTmutMatrix_refined function.
#' @param MT_variants the mtSNV table with format the same as variables generated by readMTvar_10x or readMTvar function.
#' @param MT_coverage the mitochondrial coverage information with content the same as variables generated by readCoverage_10x or readCoverage function.
#' @return a data.frame with annotation of mutation list muts.
#' @export
#' @examples mut_inf_extr(muts, donor_cell_ref, receiver_cell_ref, mutMatrix_processed, MT_variants, MT_coverage)

mut_inf_extr <- function(muts, donor_cell_ref, receiver_cell_ref, mutMatrix_processed, MT_variants, MT_coverage)
{
	t.results <- sapply(muts, function(t_mut) {
		t_pos <- strsplit(t_mut, '_')[[1]][2] ;
		
		donor_mutMa <- mutMatrix_processed[t_mut, donor_cell_ref] ;
		receiver_mutMa <- mutMatrix_processed[t_mut, receiver_cell_ref] ;
		
		nCell_donor <- sum(!is.na(donor_mutMa)) ;
		nCell_receiver <- sum(!is.na(receiver_mutMa)) ;
		
		mFrac_donor <- sum(donor_mutMa>0, na.rm=TRUE)/sum(donor_mutMa>=0, na.rm=TRUE) ;
		mFrac_receiver <- sum(receiver_mutMa>0, na.rm=TRUE)/sum(receiver_mutMa>=0, na.rm=TRUE) ;
		
		vaf_avg_donor <- mean(donor_mutMa, na.rm=TRUE) ;
		vaf_avg_receiver <- mean(receiver_mutMa, na.rm=TRUE) ;

		donor_cov <- MT_coverage[t_pos, donor_cell_ref] ;
		receiver_cov <- MT_coverage[t_pos, receiver_cell_ref] ;
		t_reads_donor <- sum(donor_cov) ;
		t_reads_receiver <- sum(receiver_cov) ;
		
				
		MT_table_donor <- MT_variants[MT_variants$Cell%in%donor_cell_ref, ] ;
		s_reads_donor <- sum(MT_table_donor$s_reads[MT_table_donor$ID==t_mut]) ;
		
		MT_table_receiver <- MT_variants[MT_variants$Cell%in%receiver_cell_ref, ] ;
		s_reads_receiver <- sum(MT_table_receiver$s_reads[MT_table_receiver$ID==t_mut]) ;
		# s_reads_donor <- sum(donor_cov*mutMatrix_Hcover[t_mut, donor_cell_ref], na.rm=TRUE) ;
		# s_reads_receiver <- sum(receiver_cov*mutMatrix_Hcover[t_mut, receiver_cell_ref], na.rm=TRUE) ;

		vaf_po_donor <- s_reads_donor/t_reads_donor ;
		vaf_po_receiver <- s_reads_receiver/t_reads_receiver ;
		
		t.r <- c(nCell_donor=nCell_donor, nCell_receiver=nCell_receiver, mFrac_donor=mFrac_donor, mFrac_receiver=mFrac_receiver, vaf_avg_donor=vaf_avg_donor, vaf_avg_receiver=vaf_avg_receiver, s_reads_donor=s_reads_donor,  s_reads_receiver=s_reads_receiver, t_reads_donor=t_reads_donor, t_reads_receiver=t_reads_receiver, vaf_po_donor=vaf_po_donor, vaf_po_receiver=vaf_po_receiver) ;
		
		return(t.r) 
	})
	
	t.results <- data.frame(t(t.results)) ;
	return(t.results) ;
}

