#' The expected postive cell numbers by add 'AND' gate to random ranks
#'
#' This function will returen the postive calls from random ranks.
#' @param MTreceiver_pre the predicted results of MERCI, which a the file generated by Integ_rank_pre function.
#' @param top_rank the top percentage of rank scores, the positive calls will generated based on this cutoff, default=20.
#' @param Number_R the times of randomly permutation, default=10.
#' @return a dataframe with the number of positive calls of MERCI and random.
#' @export
#' @examples Random_perfs_test(Treceiver_pre, top_rank=50, Number_R=1000)

Random_perfs_test <- function(MTreceiver_pre, top_rank=20, Number_R=10)
{
	cutoff <- top_rank *0.01 ;
	t_perf <- c() ;
	pre_cellNum <- nrow(MTreceiver_pre) ;
	for(i in 1:Number_R)
	{				
		R_rank1 <- sample(1:pre_cellNum) ;
		names(R_rank1) <- rownames(MTreceiver_pre) ;
		R_rank2 <- sample(1:pre_cellNum) ;
		names(R_rank2) <- rownames(MTreceiver_pre) ;
		
		break_point <- ceiling(quantile(1:length(R_rank1), cutoff)) ;
		R_rank1 <- sort(R_rank1, decreasing=TRUE)  ;
		R_rank2 <- sort(R_rank2, decreasing=TRUE) ;

		pa.list1 <- names(R_rank1)[1:break_point] ;
		pa.list2 <- names(R_rank2)[1:break_point] ;
		
		R_pre.positive <- Reduce(intersect, list(pa.list1, pa.list2)) ;
		t_perf <- c(t_perf, length(R_pre.positive)) ;
	}
	
	N <- sum(MTreceiver_pre$prediction=='Receiver') ;
	names(t_perf) <- paste('random', 1:Number_R) ;
	t.results <- c(pre_CellNum=N, t_perf) ;
	return(t.results) ; 
}
	
