#' Read in the mitochondrial read coverage inforamtion
#'
#' This function read in MT coverage inforamtion (*.MT_Coverage.csv) generated by MERCI-mtSNP, works for data types: smart-seq2, bulk RNA-seq, scATAC-seq, bulk ATAC-seq.
#' @param CoverFile The path to .MT_Coverage.csv file generated by MERCI-mtSNP.
#' @return a data.frame of MT coverage inforamtion
#' @export
#' @examples readCoverage(CoverFile='./MT_Coverage.csv')

readCoverage <- function(CoverFile)
{
	MT_coverage <- read.csv(CoverFile, row.names=1) ;
	MT_coverage$depth <- apply(MT_coverage, 1, sum) ;
	return(MT_coverage) ;
}

